version: '3'
services:
  backend:
    container_name: nodejs
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    restart: always

  
  database:
    container_name: mysql
    image: mysql:8.0.37
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=conbo2chan
      - MYSQL_DATABASE=TMDT
    ports:
      - '3306:3306'
    volumes: 
      - ./db:/var/lib/mysql
  


  nginx:
    container_name: nginx
    image: nginx:1.25.5-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./frontend/login.html:/usr/share/nginx/html/login.html
  


