services:
  backend:
    container_name: nodejs
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    restart: always

  
  
  nginx:
    container_name: nginx
    image: nginx:1.25.5-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./frontend/login.html:/usr/share/nginx/html/login.html
  


